trigger:
- main

resources:
  repositories:
  - repository: verademo
    type: github
    name: mokkang/verademo
    endpoint: github

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: verademo

- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    dockerfile: $(Build.SourcesDirectory)/Dockerfile
    tags: |
      verademo:$(Build.BuildId)