trigger:
- main

resources:
  repositories:
  - repository: verademo-dont
    type: github
    name: m4ckdaddy/verademo-dont
    endpoint: mokkang

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: mokkang/verademo-dont

- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    dockerfile: $(Build.SourcesDirectory)/Dockerfile
    tags: |
      myimage:$(Build.BuildId)