
name: SCA Scan Action

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file ./app/pom.xml

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: verademo.war # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/app/target/
        # The desired behavior if no files are found using the provided path.
 #   Available Options:
  #    warn: Output a warning but do not fail the action
  #    error: Fail the action with an error message
  #    ignore: Do not output any warnings or errors, the action does not fail

#      if-no-files-found: warn # optional, default is warn#
        # Duration after which artifact will expire in days. 0 means using default retention.
 #   Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

#        retention-days: # optional
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        # Artifact name
        name: verademo.war # optional
        # Destination path
        path: ${{ github.workspace }}/app/target/*.war # optional
        
        #Testing out Docker image to be used within Github action. 
        
    - name: into-docker
  # You may pin to the exact commit or the version.
  # uses: into-docker/build-action@5f29fb51706eecee2ca550837a39350d6e119b7e
      uses: into-docker/build-action@v3
        with:
      # Version of the CLI tool
      version: # optional
      # Builder image to use
      builder: maven:3.8.3-openjdk
      # Docker image to build (in the format "name:tag")
      image: maven:3.8.3-openjdk # optional
      # Path, relative to the project root, to use for the build
      source-path: . # default is .
      # Path to write the artifacts created in the build phase to.
      artifacts-path: ${{ github.workspace }}/app/target/ # optional
      # Cache archive to create. If this file exists it will be used to provide cached files to the build.

      cache-path: # optional
      # Target platform to build for.
      #platform: # optional
      # Build profile to use
      #profile: # optional
      script: |
        - export SRCCLR_API_TOKEN=$'{{ secret.SRCCLR_API_TOKEN }}'
        - curl -sSL https://download.sourceclear.com/ci.sh | sh
